name: Build FNF Ultimate Toolkit

on:
  push:
    tags:
      - 'v*'

jobs:
  # ===== Build Windows =====
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci
      - run: npm run dist-win

      - uses: actions/upload-artifact@v4
        with:
          name: fnf-toolkit-windows
          path: dist/*.exe

  # ===== Build Linux =====
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci
      - run: npm run dist-linux

      - uses: actions/upload-artifact@v4
        with:
          name: fnf-toolkit-linux
          path: dist/*.AppImage